Model import/creation handled: Class '<class 'models.Admin'>' already has a primary mapper defined.
/var/www/ayyildiz/models.py:7: SAWarning: This declarative base already contains a class with the same class name and module name as models.Admin, and will be replaced in the string-lookup table.
  class Admin(UserMixin, db.Model):
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/var/www/ayyildiz/app.py", line 61, in <module>
    from models import Category
  File "/var/www/ayyildiz/models.py", line 7, in <module>
    class Admin(UserMixin, db.Model):
  File "/var/www/ayyildiz/venv/lib/python3.12/site-packages/sqlalchemy/orm/decl_api.py", line 842, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/var/www/ayyildiz/venv/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/ayyildiz/venv/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/ayyildiz/venv/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 576, in __init__
    self._setup_table(table)
  File "/var/www/ayyildiz/venv/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 1755, in _setup_table
    table_cls(
  File "/var/www/ayyildiz/venv/lib/python3.12/site-packages/flask_sqlalchemy/model.py", line 147, in __table_cls__
    return sa.Table(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in __new__
  File "/var/www/ayyildiz/venv/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/var/www/ayyildiz/venv/lib/python3.12/site-packages/sqlalchemy/sql/schema.py", line 429, in __new__
    return cls._new(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/ayyildiz/venv/lib/python3.12/site-packages/sqlalchemy/sql/schema.py", line 461, in _new
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'admins' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
root@srv863913:~/ayyildizhaber/deployment#